### ISSUE TITLE
Cordova 10.0.0, error after installing @cordova-plugin-agconnect/crash 

### ISSUE THREAD

**Issue by AnnaMGh** [AppGalleryConnect/agc-cordova-plugin#1]
Hi, after installing `"@cordova-plugin-agconnect/crash"` using `cordova 10.0.0` I always get this error:

```
Failed to install 'cordova-plugin-agc-crash': TypeError: Cannot read property '1' of null
	at addRepos (MY_PROJECT_PATH\plugins\cordova-plugin-agc-crash\scripts\android\helper.js:52:27)plugins\cordova-plugin-agc-crash\scripts\android\helper.js:52:27
	at Object.modifyRootBuildGradle (MY_PROJECT_PATH\plugins\cordova-plugin-agc-crash\scripts\android\helper.js:107:23)
	at module.exports (MY_PROJECT_PATH\plugins\cordova-plugin-agc-crash\scripts\android\after_plugin_install.js:22:12)
	at runScriptViaModuleLoader (C:\Users\Anna\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:157:32)
	at runScript (C:\Users\Anna\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:136:12)
	at C:\Users\Anna\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:108:40
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I tried with `crash@1.1.0` and `crash@1.0.0` but none of them work when cordova version is 10.0.0. Any idea why? Thank you.

---
UPDATE 1

Exactly the same error occures also with:
`cordova plugin add @cordova-plugin-agconnect/remoteconfig@1.1.0 --save`
`cordova plugin add @cordova-plugin-agconnect/auth@1.1.0 --save`
`cordova plugin add @cordova-plugin-agconnect/core@1.1.0 --save`

But not with:
`cordova plugin add @cordova-plugin-agconnect/applinking@1.2.0-beta.1 --save`
`cordova plugin add @cordova-plugin-agconnect/appmessaging@1.2.0-beta.1 --save`
`cordova plugin add @cordova-plugin-agconnect/cloudfunctions@1.2.0-beta.1 --save`

So I believe it might be an issue with versions under `1.2.0`

**Comment by Mayism** [comment]
@AnnaMGh Sorry to get back to you so late. The reason may be that the cordova plug-in version is incompatible with the latest Android 9.1.0 version. You can specify the Android 9.0 version to avoid this problem.
1. Run the following command to check the current Android version.
`cordova platform ls`
2. If the Android version is 9.1, run the following command to specify the version as 9.0.
`cordova platform add android@9.0`

**Comment by Mayism** [comment]
@AnnaMGh @AnnaMGh Sorry to get back to you so late. The reason may be that the cordova plug-in version is incompatible with the latest Android 9.1.0 version. You can specify the Android 9.0 version to avoid this problem.

Run the following command to check the current Android version.
`cordova platform ls`
If the Android version is 9.1, run the following command to specify the version as 9.0.
`cordova platform add android@9.0`
And we will release the version of plugin which is compatible to android 9.1. Thank for your supporting!

**Comment by Mayism** [comment]
@AnnaMGh Sorry to get back to you so late. The reason may be that the cordova plug-in version is incompatible with the latest Android 9.1.0 version. You can specify the Android 9.0 version to avoid this problem.

Run the following command to check the current Android version.
`cordova` platform ls`
If the Android version is 9.1, run the following command to specify the version as 9.0.
`cordova platform add android@9.0`
And we will release the version of plugin which is compatible to android 9.1 soon. Thank for your supporting!

**Comment by Mayism** [comment]
@AnnaMGh Sorry to get back to you so late. The reason may be that the cordova plug-in version is incompatible with the latest Android 9.1.0 version. You can specify the Android 9.0 version to avoid this problem.
1. Run the following command to check the current Android version.
`cordova platform ls `
2. If the Android version is 9.1, run the following command to specify the version as 9.0.
`cordova platform add android@9.0`
and we will release the version of plugin which is compatible to android 9.1 soon. Thank you for your support.
